# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class StudentGrades(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, subject: str=None, grade: int=None):  # noqa: E501
        """StudentGrades - a model defined in Swagger

        :param subject: The subject of this StudentGrades.  # noqa: E501
        :type subject: str
        :param grade: The grade of this StudentGrades.  # noqa: E501
        :type grade: int
        """
        self.swagger_types = {
            'subject': str,
            'grade': int
        }

        self.attribute_map = {
            'subject': 'subject',
            'grade': 'grade'
        }

        self._subject = subject
        self._grade = grade

    @classmethod
    def from_dict(cls, dikt) -> 'StudentGrades':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Student_grades of this StudentGrades.  # noqa: E501
        :rtype: StudentGrades
        """
        return util.deserialize_model(dikt, cls)

    @property
    def subject(self) -> str:
        """Gets the subject of this StudentGrades.


        :return: The subject of this StudentGrades.
        :rtype: str
        """
        return self._subject

    @subject.setter
    def subject(self, subject: str):
        """Sets the subject of this StudentGrades.


        :param subject: The subject of this StudentGrades.
        :type subject: str
        """

        self._subject = subject

    @property
    def grade(self) -> int:
        """Gets the grade of this StudentGrades.


        :return: The grade of this StudentGrades.
        :rtype: int
        """
        return self._grade

    @grade.setter
    def grade(self, grade: int):
        """Sets the grade of this StudentGrades.


        :param grade: The grade of this StudentGrades.
        :type grade: int
        """

        self._grade = grade
